actions:
  - procedure: aur.install
    info: Installing font `otf-font-awesome`
    package: ["otf-font-awesome"]

  - procedure: aur.install
    info: Installing font `nerd-fonts`
    package: ["nerd-fonts"]
