actions:
  - procedure: aur.install
    info: Installing font `otf-font-awesome`
    packages: ["otf-font-awesome"]

  - procedure: aur.install
    info: Installing font `nerd-fonts`
    packages: ["nerd-fonts"]
