depends:
  - git+https://github.com/EE-Atlas/Atlas-dots@tag=v1.0.0
  - dolphin
  - fonts
  - fuzzel
  - hypridle
  - hyprland
  - hyprlock
  - hyprpaper
  - hyprpicker
  - hyprpolkitagent
  - hyprshot
  - nwg-displays
  - sddm
  - services
  - swaync
  - waybar
