actions:
  - procedure: aur.install
    info: Installing fuzzel
    packages: ["fuzzel"]

  - procedure: os.symlink
    info: Creating fuzzel configuration symlink
    src: "./files/fuzzel"
    dst: "{{ user.config }}/fuzzel"
