actions:
  - procedure: paru.install
    info: Installing fuzzel
    package: ["fuzzel"]

  - procedure: os.symlink
    info: Creating fuzzel configuration symlink
    src: "./files/fuzzel"
    dst: "{{ user.config }}/fuzzel"
