actions:
  - procedure: aur.install
    info: Installing bluez
    packages:
      - bluez
      - bluez-utils
      - blueman

  - procedure: shell.run
    info: Enable autostart for bluetooth
    command: systemctl
    args: ["enable", "--now", "bluetooth.service"]
    privileged: true
