actions:
  - procedure: aur.install
    info: "Installing nm-connection-editor"
    packages:
      - nm-connection-editor

  - procedure: shell.run
    info: "Enable autostart for NetworkManager"
    command: systemctl
    args: ["enable", "--now", "NetworkManager"]
    privileged: true
