actions:
  - procedure: aur.install
    info: Installing hyprlock
    packages: ["hyprlock"]

  - procedure: os.symlink
    info: Creating hyprlock configuration symlink
    src: "./files/hyprlock.conf"
    dst: "{{ user.config }}/hypr/hyprlock.conf"
