actions:
  - procedure: aur.install
    info: "Installing hyprpolkitagent"
    packages: ["hyprpolkitagent"]

  - procedure: shell.run
    info: "Changing shell for user"
    command: systemctl
    args: ["enable", "--now", "hyprpolkitagent.service"]
    privileged: true
