actions:
  - procedure: aur.install
    info: Installing waybar
    packages: ["waybar"]

  - procedure: os.symlink
    info: Creating waybar config symlink
    src: "./files/waybar"
    dst: "{{ user.config }}/waybar"
